services:
  remnashop:
    &remnashop
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: "remnashop-local"
    hostname: remnashop
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - '127.0.0.1:9493:9493'

    volumes:
      - ./src:/opt/remnashop/src
      - ./logs:/opt/remnashop/logs
      - ./assets:/opt/remnashop/assets

    networks:
      - remnawave-network
    

  remnashop-taskiq-worker:
    <<: *remnashop
    container_name: "remnashop-taskiq-worker"
    hostname: remnashop-taskiq-worker
    command: taskiq worker src.infrastructure.taskiq.worker:worker 
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd

  remnashop-taskiq-scheduler:
    <<: *remnashop
    container_name: "remnashop-taskiq-scheduler"
    hostname: remnashop-taskiq-scheduler
    command: taskiq scheduler src.infrastructure.taskiq.scheduler:scheduler
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd


networks:
  remnawave-network:
    name: remnawave-network
    driver: bridge
    external: false