services:
  remnashop:
    &remnashop
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: "remnashop"
    hostname: remnashop
    restart: unless-stopped

    env_file:
      - .env
    environment:
      RESET_ASSETS: "${RESET_ASSETS:-false}"

    volumes:
      - ./logs:/opt/remnashop/logs
      - ./assets:/opt/remnashop/assets

    networks:
      - remnabot-network
    

  remnashop-taskiq-worker:
    <<: *remnashop
    container_name: "remnashop-taskiq-worker"
    hostname: remnashop-taskiq-worker
    command: taskiq worker src.infrastructure.taskiq.worker:worker 
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd
    ports:
      - "5786"


  remnashop-taskiq-scheduler:
    <<: *remnashop
    container_name: "remnashop-taskiq-scheduler"
    hostname: remnashop-taskiq-scheduler
    command: taskiq scheduler src.infrastructure.taskiq.scheduler:scheduler
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd
    ports:
      - "5784"


networks:
  remnabot-network:
    name: remnabot-network
    driver: bridge 
    external: false