name: Remnashop - Release

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ”– Get latest tag
        id: latest-tag
        uses: JinoArch/get-latest-tag@latest

      - name: ğŸ—ï¸ Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/remnashop:Latest
            ghcr.io/remnashop:${{ github.ref_name }}

      - name: ğŸ“¦ Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: v${{ github.ref_name }}
          generate_release_notes: false
          body: |
            # ğŸ› Remnashop v${{ github.ref_name }} 
            [![Telegram Group](https://img.shields.io/badge/public_group-white?style=social&logo=Telegram&logoColor=blue)](https://t.me/remna_shop)
            [![Remnawave](https://img.shields.io/badge/remnawave-white?style=social&logo=Telegram&logoColor=blue)](https://t.me/+xQs17zMzwCY1NzYy)

            ---

            - [Compare changes (${{ steps.latest-tag.outputs.previousTag }}...${{ steps.latest-tag.outputs.latestTag }})](https://github.com/snoups/remnashop/compare/${{ steps.latest-tag.outputs.previousTag }}...${{ steps.latest-tag.outputs.latestTag }})

            ---

            ## ğŸ³ Docker Images

            ### Latest:
            ```
            ghcr.io/remnashop:latest
            ```

            ### Versioned:
            ```
            ghcr.io/remnashop:${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
